name: Build and Push Docker Images

inputs:
  registry_endpoint:
    required: true
    type: string
    description: 'The endpoint of the container registry'
  secret_key:
    required: true
    type: string
    description: 'The secret key of the container registry'
  image_name:
    required: true
    type: string
    description: 'The name of the image to build and push'
  image_tag:
    required: true
    type: string
    description: 'The tag of the image to build and push'
  app_name:
    required: true
    type: string
    description: 'The name of the application to build and push (api, web)'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10.12.2
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry_endpoint }}
        username: nologin
        password: ${{ inputs.secret_key }}

    - name: Build Applications
      shell: bash
      run: pnpm exec nx build ${{ inputs.app_name }}

    - name: Build Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: apps/${{ inputs.app_name }}/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:${{ github.sha }}
          ${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        push: true
