name: Deploy Applications

on:
  push:
    branches:
      - main
      - chore/container-api-deployment
  release:
    types: [published]

jobs:
  build-api-development:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/workflows/actions/build-and-push-docker
        with:
          registry_endpoint: ${{ vars.SCW_API_REGISTRY_ENDPOINT }}
          secret_key: ${{ secrets.SCW_SECRET_KEY }}
          image_name: toolbox-api
          image_tag: development
          app_name: api

  build-web-development:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'Building web development'

  deploy-api-development:
    needs:
      - build-api-development
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'Deploying api development'

  deploy-web-development:
    needs:
      - deploy-api-development
      - build-web-development
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'Deploying web development'
