name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform-actions.yml

    permissions:
      contents: read
      pull-requests: write

    with:
      action: plan
