name: 'Terraform Apply'

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  terraform-apply:
    uses: ./.github/workflows/terraform-actions.yml

    permissions:
      contents: read
      pull-requests: write

    with:
      action: apply
